version: '3'

volumes:
    mongodb_volume:
    postgres_volume:

services:
  tennis_matchmaking:
    image: 'bot'
    container_name: app
    depends_on:
      - db
      - mongodb
    environment:
        - BOT_TOKEN =${BOT_TOKEN}
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
        - SPRING_DATASOURCE_USERNAME=compose-postgres
        - SPRING_DATASOURCE_PASSWORD=compose-postgres
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - spring.data.mongodb.host=mongodb:27017
    restart: always


  db:
    image: 'postgres:13.1-alpine'
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - 5432:5432
    restart: always

  mongodb:
    image: 'mongo:latest'
    volumes:
      - mongodb_volume:/data/db
    container_name: mongodb
    ports:
      - 27017:27017
    restart: always
